<script type="text/javascript">
    $(document).ready(function(){
    $("input").blur(function(){
    	if(this.value == "" || this.value == null)
    	{
    		return;
    	}
        var formElementId = ($(this).parent().prev().find('label').attr('for'));
        doValidationPlant(formElementId,'../validation/validate?form=gasturbine');
   });
});
</script>

<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');

$this->tabPane("GTList", $this->form, array('title' => 'Gasturbine Add'));
echo $this->tabContainer("GTList", array());
echo $this->errorMessage;
?>
