<script type="text/javascript" src="../js/timeago.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("abbr.timeago").timeago();
        jQuery.timeago.settings.allowFuture = true;
    });
    
    function showMore(x)
	{
		var upperlimit = ((x*10)-1)+10;
		$.ajax({
            data: "ul=" + upperlimit + "&mode=paginate",
            url: "/notification/view",
            success: function(msg){
                if (msg != ''){
                    $("#notifications").html(msg);
                }
            }
        });		
	}
	function showLess(x)
	{
		$.ajax({
            data: "ul=" + ((x*10)-1) + "&mode=paginate",
            url: "/notification/view",
            success: function(msg){
                if (msg != ''){
                    $("#notifications").html(msg);
                }
            }
        });		
	}
</script>
<br/>
<div id = 'notifications'>
    <div style='margin-top: 10px;  margin-left: 25px; margin-bottom: 10px; width: 540px;'><div style='font-size: 18px; color: #2e4e68;'><b style="background: url(../images/notification.png) left no-repeat; padding-left: 25px;">Notifications</b></div></div>
    <br/>
    <?php
    $j = 1;	
	$dbconfig = Zend_Db_Table_Abstract::getDefaultAdapter();
    foreach ($this->notifications as $note) {
        echo "<div class = 'note_element ui-corner-top' onmouseover=\"glow(this,'c1e199')\" onmouseout='unglow(this)' id = 'notification " . $j . "'>";
    	echo "<img src='../images/" . $note['category'] . ".png' height='36px' width='36px' />";
	
		$ts = $note['timeupdate'];
        $timeiso = date('c', strtotime($ts));
        $timenml = date('M d, Y', strtotime($ts));
        echo "<span style='margin-left:10px; float:right;'><font size=2 color=#808080><abbr class='timeago' title='$timeiso'>$timenml</abbr></font></span>";
		
        switch($note['category']) {
			case "plant":
				$plant = new Model_DbTable_Plant($dbconfig,$note['catid']);
				echo "Plant - <a href = '/plant/view?id=" . $plant->getPlantId() ."'>" . $plant->getPlantName() . "</a> was added to " . Zend_Registry::get('usergroup') . " usergroup";
				break;
			case "schedule":
				$conference = new Model_DbTable_Conference($dbconfig,$note['catid']);
				echo "Schedule was added to the conference - <a href = '/conference/view?id=" . $conference->getConferenceId() . "#ui-tabs-1'>" . $conference->getYear() . "(" . $conference->getPlace() . ")</a>";
				break;
			case "finding":
				$finding = new Model_DbTable_Gtdata($dbconfig,$note['catid']);
				$gt = new Model_DbTable_Gasturbine($dbconfig,$finding->getGTId());
				$user = new Model_DbTable_Userprofile($dbconfig,$finding->getUserUpdate());
				if(!$note['edit']) {
					echo "<b>Finding</b> - <a href = '/findings/view?id=" .$finding->getId() . "'>" . $finding->getTitle() . "</a> was added to <b>" . $finding->getSystemName()
					. "/" . $finding->getSubSystemName() . "</b><br><b>Gasturbine</b> - <a href ='/gasturbine/view?id=" . $gt->getGTId() . "'>" . $gt->getGTName() . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				else {
					echo "<b>Finding</b> - <a href = '/findings/view?id=" .$finding->getId() . "'>" . $finding->getTitle() . "</a> belonging to <b>" . $finding->getSystemName()
					. "/" . $finding->getSubSystemName() . "</b> was edited. <br><b>Gasturbine</b> - <a href ='/gasturbine/view?id=" . $gt->getGTId() . "'>" . $gt->getGTName() . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				break;
			case "upgrade":
				$upgrade = new Model_DbTable_Gtdata($dbconfig,$note['catid']);
				$gt = new Model_DbTable_Gasturbine($dbconfig,$upgrade->getGTId());
				$user = new Model_DbTable_Userprofile($dbconfig,$upgrade->getUserUpdate());
				if(!$note['edit']) {
					echo "<b>Upgrade</b> - <a href = '/upgrades/view?id=" .$upgrade->getId() . "'>" . $upgrade->getTitle() . "</a> was added to <b>" . $upgrade->getSystemName()
					. "/" . $upgrade->getSubSystemName() . "</b><br><b>Gasturbine</b> - <a href ='/gasturbine/view?id=" . $gt->getGTId() . "'>" . $gt->getGTName() . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				else {
					echo "<b>Upgrade</b> - <a href = '/upgrades/view?id=" .$upgrade->getId() . "'>" . $upgrade->getTitle() . "</a> belonging to <b>" . $upgrade->getSystemName()
					. "/" . $upgrade->getSubSystemName() . "</b> was edited. <br><b>Gasturbine</b> - <a href ='/gasturbine/view?id=" . $gt->getGTId() . "'>" . $gt->getGTName() . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				break;
			case "lte":
				$lte = new Model_DbTable_Gtdata($dbconfig,$note['catid']);
				$gt = new Model_DbTable_Gasturbine($dbconfig,$lte->getGTId());
				$user = new Model_DbTable_Userprofile($dbconfig,$lte->getUserUpdate());
				if(!$note['edit']) {
					echo "<b>LTE</b> - <a href = '/lte/view?id=" .$lte->getId() . "'>" . $lte->getTitle() . "</a> was added to <b>" . $lte->getSystemName()
					. "/" . $lte->getSubSystemName() . "</b><br><b>Gasturbine</b> - <a href ='/gasturbine/view?id=" . $gt->getGTId() . "'>" . $gt->getGTName() . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				else {
					echo "<b>LTE</b> - <a href = '/lte/view?id=" .$lte->getId() . "'>" . $lte->getTitle() . "</a> belonging to <b>" . $lte->getSystemName()
					. "/" . $lte->getSubSystemName() . "</b> was edited. <br><b>Gasturbine</b> - <a href ='/gasturbine/view?id=" . $gt->getGTId() . "'>" . $gt->getGTName() . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				break;
			case "forum_topic":
				$topic = new Model_DbTable_Forum_Topics($dbconfig,$note['catid']);
				$topicdata = $topic->getTopicData();
				
				$forum = new Model_DbTable_Forum_Forums($dbconfig,$topicdata['forum_id']);
				$forumdata = $forum->getForumData();
				
				$user = new Model_DbTable_Userprofile($dbconfig,$note['userupdate']);
				
				if(!$note['edit']) {
					echo "<b>Topic</b> - <a href = '/forums/viewtopic.php?f=" . $forumdata['forum_id'] . "&t=" . 
					$topicdata['topic_id'] . "'>" . $topicdata['topic_title'] . "</a> was added to forum - 
					<a href = '/forums/viewforum.php?f=" . $forumdata['forum_id'] . "'>" . $forumdata['forum_name'] . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}				
				else {
					echo "<b>Topic</b> - <a href = '/forums/viewtopic.php?f=" . $forumdata['forum_id'] . "&t=" . 
					$topicdata['topic_id'] . "'>" . $topicdata['topic_title'] . "</a> of forum - 
					<a href = '/forums/viewforum.php?f=" . $forumdata['forum_id'] . "'>" . $forumdata['forum_name'] . "</a> was edited";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
				break;
			case "forum_post":
				$post = new Model_DbTable_Forum_Posts($dbconfig,$note['catid']);
				$postdata = $post->getPostData();
				
				$topic = new Model_DbTable_Forum_Topics($dbconfig,$postdata['topic_id']);
				$topicdata = $topic->getTopicData();
				
				$forum = new Model_DbTable_Forum_Forums($dbconfig,$topicdata['forum_id']);
				$forumdata = $forum->getForumData();
				
				$user = new Model_DbTable_Userprofile($dbconfig,$note['userupdate']);
				
				if(!$note['edit']) {
					echo "<b>Post</b> - <a href = '/forums/viewtopic.php?f=" .$forumdata['forum_id'] . "&t=" . $topicdata['topic_id'] . "#p" . $postdata['post_id'] . "'>" . $postdata['post_subject'] . "</a> was added to topic - <a href = '/forums/viewtopic.php?f=" . $forumdata['forum_id'] . "&t=" . 
					$topicdata['topic_id'] . "'>" . $topicdata['topic_title'] . "</a> of forum - 
					<a href = '/forums/viewforum.php?f=" . $forumdata['forum_id'] . "'>" . $forumdata['forum_name'] . "</a>";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}				
				else {
					echo "<b>Post</b> - <a href = '/forums/viewtopic.php?f=" .$forumdata['forum_id'] . "&t=" . $topicdata['topic_id'] . "#p" . $postdata['post_id'] . "'>" . $postdata['post_subject'] . "</a> of topic - <a href = '/forums/viewtopic.php?f=" . $forumdata['forum_id'] . "&t=" . 
					$topicdata['topic_id'] . "'>" . $topicdata['topic_title'] . "</a> belonging to forum - 
					<a href = '/forums/viewforum.php?f=" . $forumdata['forum_id'] . "'>" . $forumdata['forum_name'] . "</a> was edited.";
					if($user->getPlantId() != 1)
						echo "<br><i style = 'font-size:12px'>by <a href = '/userprofile/view?id=" . $user->getUserId() . "'>" . $user->getFullName() . "</a> - <a href = '/plant/view?id=" . $user->getPlantId() . "'>" . $user->getPlantName() . "</a></i>";
					else 
						echo "<br><i style = 'font-size:12px'>by " . $user->getFullName() . "</i>";
				}
			default:
				
				break;
        }
        echo "</div>";
        $j++;
        if($j == $this->ul+1){
        	$x = (int)($j/10);
            echo "<span id='note-view' onClick='showMore($x)' class='note-link'>Show More</span>";
        }
		
    }
    if($j > 10)
    {
    	$x = (int)($j/10)-1;
		if($j%10 != 0)
		{
			$x++;
		}
    	echo "<span id='note-view' onClick='showLess($x)' class='note-link'>Show Less</span>";
    }
	if(count($this->notifications) == 0)
	{
		echo "<center><i>No notifications to display</i></center>";
	}
    ?>
</div>