<?php
$finding = $this->finding;
$this->finding = $this->finding->getData();
if($this->allowed)
{
	$editlink = "<div style='float:left;' class='gt-edit'><a href = '/findings/edit?id=" . $this->finding['id'] . "' style='color: #719b3e;'>Edit</a></div>";
}

$content = "<div class='gtdata-title'>".$this->finding['title'];
if($finding->getSubSystemName() == "-")
{
	$content = $content." <span style='color:#77B464;'>".$finding->getSystemName() ."</span>";
}
else
{
	$content = $content." <span style='color:#77B464;'>".$finding->getSystemName() . "/" . $finding->getSubSystemName() ."</span>";
}
$content = $content." <span style='color:#268FBB;'>".$this->gt['GTName']."</span><br/>";
if($this->finding['EOH'] != 0 && $this->finding['EOH'] != "")
	$content = $content." <span style='color:#268FBB;'><b>EOH at Occurence</b>: ". $this->finding['EOH']."</span>";
if($this->finding['DOF'] != "" && $this->finding['DOF'] != "0000-00-00")
	$content = $content." <span style='color:#268FBB;'><b>Date of Finding</b>: ".$this->finding['DOF']."</span>";
if($this->finding['TOI'] != "")
	$content = $content." <span style='color:#268FBB;'><b>Type of Inspection</b>: ".$this->finding['TOI']."</span>";
$content = $content."<br><span style='color:#268FBB; font-size: 12px; font-style: normal; font-style:italic;'><b>Updated On</b> ".$this->finding['updatedate']."</span></div>";
$content = $content."<div class='gtdata-data'>".$this->finding['data']."</div>";

$list = "<table>";
$ilist = "<table>";
$src['doc'] = '/images/word.png';
$src['docx'] = '/images/word.png';
$src['ppt'] = '/images/ppt.png';
$src['pptx'] = '/images/ppt.png';
$src['xls'] = '/images/excel.png';
$src['xlsx'] = '/images/excel.png';
$src['pdf'] = '/images/pdf.png';

foreach($this->attachmentList as $attach){
	$ext = $attach->getFileExtension();	
	if(in_array($ext,array('jpg','jpeg','png','gif'))){
		$data = $attach->getContent();
		$isrc = "uploads/" . str_replace(' ','',$attach->getTitle()) . "." . $ext;
		file_put_contents($isrc,$data);
		$dest = "uploads/th-" . $this->finding['id'] . "-" . $attach->getId() . "." . $ext;		
		Model_Functions::getThumbnail($isrc,$dest,300,300);
		$ilist .= "<tr><td><img src = '/$dest'></td><td><a href='/attachment/view?id=" . $attach->getId() . "'>" . $attach->getTitle() . "</a></td></tr>";
	}
	else {
		$list .= "<tr><td><img src = '" . $src[$ext] . "'></td><td><a href='/attachment/view?id=" . $attach->getId() . "'>" . $attach->getTitle() . "</a></td></tr>";
	}
}
$list .= "</table>";
$ilist .= "</table>";
$list .= $ilist;
if($list == "<table></table><table></table>")
	$list="<span style='color:#d95e1c;'>No Attachments Added</span>";
$content = $content."<div class='gtdata-presentations'><div style='font-size: 16px; padding-bottom: 5px;'>Attachments:</div>$list</div>";

$content = $content .$editlink;

$content = $content . "<form action = '/reports/generate' method = 'post' style='float:right'>
	<input type = 'hidden' name = 'type' value = 'finding'>
	<input type = 'hidden' name = 'id' value = '".$this->finding['id']."'>
	<input class = 'gt-report' type = 'submit' name = 'report' value = 'Generate Finding Report'>
</form>";
$content = $content . "<div align='right'>
	<form action = '/reports/configure?id=".$this->finding['id']."&type=gtdataview' method = 'post'>
		<input class = 'gt-configure	' type = 'submit' name = 'reportgen' value = 'Configure Report'>
	</form>
</div>";
$this->tabPane("findingView",$content,array('title' => 'Finding 	 View'));
echo $this->tabContainer("findingView",array());
?>