<!--<form id="file_upload_form" method="post" enctype="multipart/form-data" action="/attachments/upload">
<input name="file" id="file" size="27" type="file" /><br />
<input type="submit" id = "upload" name="action" value="Upload" /><br />
<iframe id="upload_target" name="upload_target" src="" style="width:0;height:0;border:0px solid #fff;"></iframe>
</form>

<script type = "text/javascript">
	function init() {
		document.getElementById('file_upload_form').onsubmit=function() {
			document.getElementById('file_upload_form').target = 'upload_target'; //'upload_target' is the name of the iframe
		}
	}
	window.onload=init;
</script>-->
<script type = "text/javascript" src = "/js/file_ext_check.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
	    $("input").blur(function(){
	    	if(this.value == "" || this.value == null)
	    	{
	    		return;
	    	}
	        var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidationPlant($(this).attr('id'),'../validation/validate?form=attachment');
	   });
	});
</script>
<?php 
	echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
	echo $this->form; 
?>