<?php
if (!count($this->attachments)) {
    echo "<center>No Attachments Added</center>";
} else {
?>
    <table cellspacing='0' cellpadding='0' onmouseover='tablecloth();'>
        <thead>
            <tr>
                <th>Title</th>
                <th>File Type</th>
                <th>User</th>
                <th>Date</th>
            </tr>
        </thead>

        <tbody>
<?php for ($i = 0; $i < count($this->attachments); $i++) : ?>
                <tr>
                    <td>
                        <a href = "/attachment/view?id=<?php echo $this->attachments[$i]->getId(); ?>"><?php echo $this->attachments[$i]->getTitle(); ?></a><br>
        <?php
        $attach_data = $this->attachments[$i]->getData();
        ?></td>
            <td><?php echo $this->attachments[$i]->getFiletype(); ?></td>
                    <td><?php echo $this->attachments[$i]->getUsername(); ?></td>
                    <td><?php echo $attach_data['updatedAt']; ?></td>
                <?php if ($this->allowed) : ?>
                <td>
                    <form action = "/attachment/delete?id=" <?php echo $this->attachments[$i]->getId(); ?> method = "get">
                        <input type = 'submit' class = 'gt-delete' name = 'delete' value = 'Delete'>
                    </form>
                </td>
<?php endif; ?>
            </tr>
            <?php endfor; ?>
            </tbody>
        </table>
<?php } ?>

<?php 
	if($this->allowed){
		echo "<form action = '/attachment/add' method = 'post'>";
		echo "<input type = 'submit' class = 'gt-add' value = 'Add New Attachment'>";
		if($this->mode == 'conf'){
			echo "<input type = 'hidden' name = 'cid' value = '$this->id'>";
		}
		echo "</form>";
	}
?>