<script type = 'text/javascript' src = '/js/file_ext_check.js'></script>
<script type = "text/javascript">
	$(document).ready(function(){
		var data;
		var json;
		var title;
		var modeId;
		var mode;
		var name;
		$("#attach-box").click(function(){
			$("#attach-form").dialog({width:'auto',height:'auto',title:'Add a new attachment'});
			$("#attachTitle").val("");
			$("input:file").val("");
		});		
		function startUpload(){			
		    return true;
	    }
	    
	    function stopUpload(data){
		    return true;
	    }
	});
</script>
	<?php
	if (!count($this->attachments)) {
	    echo "<center>No Attachments Added</center>";
		$style = "style='display:none'";
	} 
	?>
    <table cellspacing='0' cellpadding='0' id = 'attach-table' <?php echo $style; ?> onmouseover='tablecloth();'>
        <thead>
            <tr>
                <th>Title</th>
                <th>File Type</th>
                <th>Added By</th>
                <th>Date</th>
            </tr>
        </thead>

        <tbody id = 'attachments-list'>
<?php for ($i = 0; $i < count($this->attachments); $i++) : ?>
                <tr>
                    <td>
                        <a href = "/attachment/view?id=<?php echo $this->attachments[$i]->getId(); ?>"><?php echo $this->attachments[$i]->getTitle(); ?></a><br>
        <?php
        $attach_data = $this->attachments[$i]->getData();
        ?></td>
            <td><?php echo $this->attachments[$i]->getFiletype(); ?></td>
                    <td><?php echo $this->attachments[$i]->getUsername()." - ".$this->attachments[$i]->getUserPlantName(); ?></td>
                    <td><?php echo $attach_data['updatedAt']; ?></td>
                <?php if ($this->allowed) : ?>
                <td>
                    <form action = "/attachment/delete" method = "post">
                    	<input type = "hidden" name = "attachmentId" value = "<?php echo $this->attachments[$i]->getId();?>">
                    	<?php
                    		if($this->mode == "conf")
                    			$name = 'cid';
							else 
								$name = 'gtid';
                    	?>
                    	<input type = 'hidden' name = '<?php echo $name;?>' value = <?php echo $this->id;?>>
                        <input type = 'submit' class = 'gt-delete' name = 'delete' value = 'Delete'>
                    </form>
                </td>
<?php endif; ?>
            </tr>
            <?php endfor; ?>
            </tbody>
        </table>

<?php
	if($this->allowed){
		echo "<button class = 'gt-add' id='attach-box'>Add new attachment</button>";
		echo "<div id='attach-form' style='display:none'>$this->attachmentForm</div>";
		echo "<span id = 'mode' style='display:none'>$this->mode</span>";
		echo "<span id = 'modeId' style = 'display:none'>$this->id</span>";
		echo "<span id = 'source' style='display:none'>list</span>";
	}
?>
<iframe id="upload_target" name="upload_target" src="#" style="display:none"></iframe>