<script type = "text/javascript" src = "/js/ajaxupload.3.6.js"></script>
<script type = "text/javascript">
	var imageNo = 0;
	
	if(document.getElementById("imageNo").innerHTML != "") {
		imageNo = parseInt(document.getElementById("imageNo").innerHTML);
	}
	
	function showImg(id){
            document.getElementById("large-img").src = "/uploads/gallery/photo_" + id + ".jpg";
            $("#photo-box").dialog({
            	height:'auto',
            	width:'auto',
            	title:$("#img-"+id).attr("alt"),
            	my:'center',
            	at:'center',
            	of:window
           	});
    }
        
	$(document).ready(function(){
		new AjaxUpload("#image",{
			action: '/gallery/upload',
			name : 'image',
			onSubmit : function(file,ext){
				this.disable();
			},
			onComplete: function(file, response){
	            this.enable();
	            if(response[0] != "{")
	            {
	            	alert("Filename seems to have invalid characters. Rename the file and try again");
	            	return;
	            }
	            var data = response.split("<");
	            var json = eval("(" + data[0] + ")");
	            var content = "";
	            var colNo;
	            var rowNo;
	            if(json.error == "1"){
	            	alert("Filename seems to have invalid characters. Rename the file and try again");
	            	return;
	            }
	            $("#no-photos").remove();	
	            $.ajax({	            	
	            	type:"POST",
	            	data:"cid=" + $("#cid").val() + "&tag=" + $("#tag").val() + 
	            	     "&imgPath="+encodeURI(json.imgPath)+"&thumbPath="+encodeURI(json.thumbPath),
	            	     
	            	dataType:"json",
	            	url:"/gallery/add",
	            	success:function(msg){
	            		if(msg != ''){	            			
							rowNo = Math.floor(imageNo/3);
							if(imageNo == 0 || imageNo%3 == 0){
								content = "<tr id = 'row-" + rowNo + "'><td id = 'img" + rowNo + "-0'><img src = '" + msg.thumbPath + "' id = 'img-" + msg.imgId + "' alt = '"  + msg.tag + "' onclick='showImg(" + msg.imgId + ")'><form action = '/gallery/delete' method = 'post'><input type = 'submit' class = 'gt-delete' value=''><input type = 'hidden' name = 'photoId' value = '" + msg.imgId + "'></form></td>" +
								               "<td id = 'img" + rowNo + "-1'></td>" +
								               "<td id = 'img" + rowNo + "-2'></td>";								
								$("#image").append(content);
							}		
							else {
								colNo = imageNo - (rowNo*3);							
								$("#row-" + rowNo).append("<td id = 'img" + rowNo + "-" + colNo + "'><img src = '" + msg.thumbPath + "' alt = '" + msg.tag + "' id = 'img-" + msg.imgId + "' onclick='showImg(" + msg.imgId + ")'><form action = '/gallery/delete' method = 'post'><input type = 'submit' class = 'gt-delete' value=''><input type = 'hidden' name = 'photoId' value = '" + msg.imgId + "'></form></td>");
							}
							imageNo++;
	            		}
                        $("#gallery-form").dialog('close');
	            	}
	            });
	        }
		});
		
		$("#add-photo").click(function(){
        	$("#tag").val("");
			$("#gallery-form").dialog({title:"Add a new Photo",width:'auto',height:'auto'});
		});
	});
</script>
<div id = "gallery-form" style="display:none">
	<?php echo $this->galleryForm; ?>
	<input type = 'hidden' id = 'cid' value = '<?php echo $this->cid;?>'>
</div>
<div id ="photo-box"style="display:none"><img id='large-img'></div>
<table id="image">
	<?php
		$imageNo = 0;
		$files = glob('uploads/*');
		foreach($files as $file){
		  if(is_file($file))
		    unlink($file);
		}
		if(!count($this->photos)){
			echo "<center><span id='no-photos'>No photos added</span></center>";
		}
		foreach($this->photos as $photo){
			$thumbPath = "uploads/".$photo['photoId'].".jpg";
			file_put_contents($thumbPath,$photo['data']); 
			$row = floor($imageNo/3);
			$colNo = $imageNo - ($rowNo*3);
			if($imageNo == 0 || $imageNo%3 == 0){
				echo "<tr id = 'row-" . $row . "'>";
			}
			echo "<td id = 'img" . $row . "-$colNo'><img src = '/"  . 
			      $thumbPath . "' id = 'img-" . $photo['photoId'] . 
			      "' alt = '"  . $photo['tag'] . "' onclick='showImg(" . 
			      $photo['photoId'] . ")'><br><form action = '/gallery/delete' 
			      method = 'post'><input type = 'submit' class = 'gt-delete' value = ''>
			      <input type = 'hidden' name = 'photoId' value = '" . $photo['photoId'] . "'></form></td>";
				  
			if(($imageNo+1)%3==0 && $imageNo != 0){
				echo "</tr>";
			}
			$imageNo++;
		}
		echo "<span id = 'imageNo' style='display:none'>$imageNo-1</span>";
	?>	
</table>
<?php
	if($this->allowed){
		echo "<button id='add-photo' class = 'gt-add'>Add Photo</button>";
	}
?>