<script type="text/javascript">
    $(document).ready(function(){
    	$("input").blur(function(){
	    	if(this.value == "" || this.value == null)
	    	{
	    		return;
	    	}
	      	var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidationPlant(formElementId,'../validation/validate?form=userprofile');
	   });
    });
</script>
<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
echo $this->adminId;
//echo $this->form;
$this->tabPane("UPEdit", $this->form, array('title' => 'User profile - Edit'));
echo $this->tabContainer("UPEdit", array());
echo "<a href = '" . $this->baseUrl() . "/userprofile/changepassword'> Change Password </a>";
?>
