<script type = "text/javascript" src = "/js/attachUpload.js"></script>
<script type = "text/javascript">
	$(document).ready(function(){
		$("#sysId").change( function() {
	        $.ajax({
	            type: "POST",
	            data: "sid=" + $(this).val(),
	            url: "/gtsubsystems/list",
	            success: function(msg){
	                if (msg != ''){
	                    $("#subSysId").html(msg).show();
	                }
	            }
	        });
	    });
	    
	    $("input").blur(function(){
	    	if(this.value == "" || this.value == null){
	    		return;
	    	}
	        var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidationPlant($(this).attr('id'),'../validation/validate?form=gtdata&type=lte');
	   });	
	});
</script>

<?php
	echo $this->headScript()->prependFile($this->baseUrl().'/js/tiny_mce/tiny_mce.js');
	echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
	$lastUpdateInfo = "<i>Last updated by " . Model_DbTable_Userprofile::getUserName($this->userupdate) . " on " .
	                  $this->updatetime . "</i>";
	$this->message = "<br><div class ='errors'>" . $this->message . "</div>";				  
	$this->tabPane("gtdataEdit",$this->form.$lastUpdateInfo,array('title' => $this->typeTitle . ' Edit'));
	echo $this->tabContainer("gtdataEdit",array());
	echo $this->message;
	$this->spinner = "<div id = 'spinnerimage' style = 'display:none'>Uploading ... <img src = '/images/spinner.gif'></div>";
?>
<script type="text/javascript" src='/js/tinyMCEinit.js'></script>
<div style="display:none" id="attach-form">
	<?php echo $this->attachForm . $this->spinner; ?>
</div>
<span id = 'mode' style='display:none'>gt</span>
<span id = 'modeId' style = 'display:none'><?php echo $this->gtid;?></span>
<span id = 'gtdataId' style = 'display:none'><?php echo $this->id;?></span>
<span id = 'source' style = 'display:none'>edit</span>
<span id = 'added-attachments' style='display:none'>
	<?php		
		if(count($this->addedAttachments)){
			echo "<td><span id = 'attachments-head'>Attachments Added</span><br><ul id = 'attachments-list'>";
			foreach($this->addedAttachments as $attach){								
				echo "<li id = 'a-" . $attach->getId() . "'><a href = '/attachment/view?id=" . $attach->getId() . "'>" .
				     $attach->getTitle() . "</a>  <input type = 'button' id = 'del-" . $attach->getId() . 
				     "' class = 'gt-delete' onclick = 'del_attach(" . $attach->getId() . ")'> 
				     <a href='#' onclick='unlink(" . $attach->getId() . ")'>Unlink</a></li>"; 
			}
			echo "</ul></td>";
		}
	?>
</span>