<?php
	if(!count($this->lteList))
	{
		echo "<center>No lte Added</center>";
		
	}
	else {
		echo"<table cellspacing='0' cellpadding='0' onmouseover='tablecloth();'>
		<tr>
		<th>Title</th>
		<th>System/Subsystem</th>
		<th>EOH</th>
		<th>Type of Inspection</th>
		<th>User</th>
		<th>Date</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
		</tr>";
	}
?>
<?php
foreach($this->lteList as $lte) : ?>
<tr>
<td>
<?php
echo "<a href='".$this->url(array('action'=>'view'))."?id=".$this->escape($lte->getId())."'>".$lte->getTitle()."</a><br/>";

$username = Model_DbTable_Userprofile::getUserName($lte->getUserUpdate()) . " - " . Model_DbTable_Userprofile::getUserPlantName($lte->getUserUpdate());
$fdata = $lte->getData();
?></td>
<?php if($lte->getSubSystemName() == '-') : ?>
	<td><?php echo $lte->getSystemName(); ?></td>
<?php else : ?>
	<td><?php echo $lte->getSystemName(); ?> / <?php echo $lte->getSubSystemName(); ?></td>
<?php endif; ?>

<?php if($fdata['EOH'] != "") : ?>
	<td><?php echo $fdata['EOH']; ?></td>
<?php else : ?>
	<td> </td>
<?php endif; ?>
<?php if($fdata['TOI'] != "") : ?>
	<td><?php echo $fdata['TOI']; ?></td>
<?php else : ?>
	<td> </td>
<?php endif; ?>

<td><?php echo $username;?></td>
<td><?php echo $this->escape($fdata['updatedate']);?></td>
<?php
    if($this->allowed) {
?>
<td><a href="/lte/edit?id=<?php echo $lte->getId(); ?>">Edit</a>
</td>
	<td><form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
	<input type="hidden" name="id" value="<?php echo $this->escape($lte->getId());?>" />
	<input class='gt-delete' type="submit" name="del" value="Delete" />
	</form>
	</td>
	<?php 
}
?>
<?php endforeach;?>

</table>
<div style='clear:both; height:5px;'>&nbsp;</div>
<?php if($this->allowed){ ?>
	<form action = '/lte/add' method = 'post'>
		<input type = 'hidden' value = '<?php echo $this->gtid;?>' name = 'gtid'>
		<input type = 'submit' value = 'Add a new LTE' class = 'gt-add'>
	</form>
<?php } ?>
<?php if(count($this->lteList) != 0) :?>
	<form action = '/reports/generate' method = 'post' style='float:right;'>
		<input type = 'hidden' name = 'type' value = 'fdatalist'>
		<input type = 'hidden' name = 'id' value = "<?php echo $this->id; ?>">
		<input class='gt-report' type = 'submit' name = 'report' value = 'Generate LTEs Report'>
	</form>
	<div align = 'right'>
		<form action = '/reports/configure?id=<?php echo $this->id;?>&type=lte' method = 'post'>
			<input class='gt-configure' type = 'submit' name = 'reportgen' value = 'Configure'>
		</form>
	</div>	
<?php endif;?>
