<script type="text/javascript">
    $(document).ready(function(){
	    $("input").blur(function(){
	    	if(this.value == "" || this.value == null)
	    	{
	    		return;
	    	}
	        var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidationPlant($(this).attr('id'),'../validation/validate?form=conference');
	   });
	});
</script>
<?php
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
echo $this->headScript()->prependFile($this->baseUrl() . '/js/tiny_mce/tiny_mce.js');
$data = $this->form;
if ($this->message == "")
    $data .= $this->message;
else
    $data .= "<div class = 'errors'>" . $this->message . "</div>";
$this->tabPane("ConfEdit", $data, array('title' => 'Edit Conference'));
echo $this->tabContainer("ConfEdit", array());
?>
<!-- TinyMCE --><script type="text/javascript" src='/js/tinyMCEinit.js'></script><!-- /TinyMCE -->