<script type = 'text/javascript'>
	function showolder(max)
	{
		if(document.getElementById('olderlink').innerHTML == "Older &gt;&gt;") {
			for( var i = 6; i <= max; i++ ) {
				document.getElementById('older'+i).style.display = 'list-item';
			}
			document.getElementById('olderlink').innerHTML = "&lt;&lt; Hide";
		}
		else {
			for( var i = 6; i <= max; i++ ) {
				document.getElementById('older'+i).style.display = 'none';
			}
			document.getElementById('olderlink').innerHTML = "Older &gt;&gt;";
		}
			
	}
</script>
<?php
	$i = 1;
	foreach($this->conferences as $conf) {
		$cid = $conf['cId'];
		if($i <= 5) {
			$content = $content . "<li><a href = '/conference/view?id=" .$cid . "'>". 
					   $conf['place'] . "</a>&nbsp;&nbsp;(".$conf['year'].")";
			if($this->allowed)
			{
				$content = $content . "<br><br>&nbsp;&nbsp;&nbsp;<a class = 'a-edit ui-corner-all' 
				           href = '/conference/edit?id=" . $cid . "'>Edit</a>&nbsp;&nbsp;&nbsp;
				           <a class = 'a-delete ui-corner-all' href = '/conference/delete?id=" . $cid . 
				           "'>Delete</a>";
			}
			$content = $content . "</li><br>";
		}
		else {
			$content = $content . "<li style = 'display:none' id = 'older".$i."'><a href = '/conference/view?id=" . 
			           $cid . "'>". $conf['place'] . "</a>&nbsp;&nbsp;(".$conf['year'].")";
			if($this->allowed)
			{
				$content = $content . "&nbsp;&nbsp;&nbsp;<a href = '/conference/edit?id=" . 
				           $cid . "'>Edit</a>&nbsp;&nbsp;&nbsp;<a href = '/conference/delete?id=" . 
				           $cid . "'>Delete</a>";
			}
			$content = $content . "<br><br></li>";
		}
		$i++;
	}
	$content = $content . "</ul>";
	if($i > 5)
	{
		$content = $content . "<br><p align = 'right'><a id = 'olderlink' href = '#' 
		           onclick = 'javascript:showolder($i-1)'>Older &gt;&gt;</a></p>";
	}
	$this->tabPane("YrList",$content,array('title' => 'Conferences'));
	echo $this->tabContainer("YrList",array());
?>